import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Journal App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-mono font-bold text-center pt-4">
          A Digital Journal Application
        </h1>
      </main>
      <section className="pl-32">
        <h2 className="text-left">Title</h2>
        <input type="text" />
      </section>
      <section>
        <h2 className="text-left pl-32">Body</h2>
      </section>
    </div>
  );
}
